nome = input("Digite o seu nome ")
print(f"Olá {nome}" )
rua = input("Digite a sua rua ")
numero = input("Digite o número ")
cidade = input("Digite a cidade ")
input(f"Endereço: Rua {rua}, {numero} - {cidade} ")
idade = input("Qual a sua idade? ")
email = input("Qual o seu email? ")
print(f"Seu cartão de cadastro está sendo processado")
print(f"----------------\nNome: {nome} \nIdade: {idade} \nEmail: {email}\n----------------")
